name: 'CI'

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Lint'
      run: make lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v2
    - name: 'Build dist bundle'
      run: make dist
    - id: vars
      run: echo "::set-output name=distpath::$(make distpath)"
    - name: 'Upload dist bundle to artifacts'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.vars.outputs.distpath }}
        path: ${{ steps.vars.outputs.distpath }}
    - name: 'Generate SHA256 checksum files'
      run: sha256sum ${{ steps.vars.outputs.distpath }} > ${{ steps.vars.outputs.distpath }}.sha256
    - name: 'Upload SHA256 checksum files to artifacts'
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.vars.outputs.distpath }}.sha256
        path: ${{ steps.vars.outputs.distpath }}.sha256

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: 'Download build artifacts'
      uses: actions/download-artifact@v2
      with:
        path: artifacts
    - name: 'Create new release'
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        prerelease: ${{ contains(github.ref, '-') }}
        files: |
          artifacts/*/*
